# Generated by Django 3.2.15 on 2022-12-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='full_name')),
                ('date', models.DateField(verbose_name='date')),
                ('num_people', models.IntegerField(verbose_name='num_people')),
                ('is_data_proc', models.BooleanField(verbose_name='is_data_proc')),
                ('time_of_day', models.CharField(max_length=15, verbose_name='time_of_day')),
                ('dishes', models.ManyToManyField(to='myapp.Dish')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hall')),
            ],
        ),
    ]
