# Generated by Django 3.2.15 on 2022-12-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DISHES',
            field=models.ManyToManyField(max_length=3, to='myapp.Dish'),
        ),
    ]
